apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: file-store-lister
  labels:
    app: file-store-lister
spec:
  selector:
    matchLabels:
      name: file-store-lister
  template:
    metadata:
      labels:
        name: file-store-lister
    spec:
      containers:
      - name: file-store-lister
        image: mansoorpervaizinstana/file-store-lister:latest
        securityContext:
            privileged: true

        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: file-store-listers
rules:
- nonResourceURLs:
  - /version
  - /healthz
  - /metrics
  - /stats/summary
  - /metrics/cadvisor
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - deployments
  - replicasets
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - daemonsets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - events
  - services
  - endpoints
  - nodes
  - nodes/stats
  - nodes/metrics
  - pods
  - replicationcontrollers
  - componentstatuses
  - resourcequotas
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: file-store-listers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: file-store-listers
subjects:
- kind: ServiceAccount
  name: file-store-listers
  namespace: mptest
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: file-store-listers
